#include <iostream>                                                                                                                                                                                     
#include <arm_neon.h>                                                                                                                                                                                   
#include <vector>                                                                                                                                                                                       
                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                           
// 1. A 矩阵 (M x K) 已在内存中按 8 行交错打包 (Interleaved packed)，                                                                                                                                   
//    即对于每一个 k，连续存放 A[0][k], A[1][k]...A[7][k]。                                                                                                                                             
// 2. W 矩阵 (K x N) 已在内存中按 16 列打包并压缩为 4-bit。                                                                                                                                             
void gemm_m4_w4a16(const float16_t* A, const uint8_t* W, float16_t* C, int M, int N, int K) {                                                                                                           
                                                                                                                                                                                                        
    // 全局常数寄存器 (分布式的 Scale 和 Bias)                                                                                                                                                          
    float16x8_t v_scale = vdupq_n_f16(0.1f);                                                                                                                                                            
    float16x8_t v_bias  = vdupq_n_f16(-0.5f);                                                                                                                                                           
                                                                                                                                                                                                        
    // 外层循环 1：沿 M 维度，每次切下 8 行        
    
    
            for (int m = 0; m < M; m += 8) {                                                                                                                                                                    
                                                                                                                                                                                                                
                // 外层循环 2：沿 N 维度，每次切下 16 列                                                                                                                                                        
                for (int n = 0; n < N; n += 16) {                                                                                                                                                               
                                                                                                                                                                                                                
                    // 定位当前 8x16 瓦片的输入指针                                                                                                                                                             
                    // 因为 A 是 8 行打包的，所以 m 所在的 8 行块的起始位置是 (m/8) * (8*K) = m * K                                                                                                             
                    const float16_t* ptr_act = A + (m * K);                                                                                                                                                     
                    // W 是 16 列打包的，16 列在 4-bit 下占 8 字节。所以 n 所在的块起始位置是 (n/16) * (K*8)                                                                                                    
                    const uint8_t* ptr_w = W + (n / 16) * (K * 8);                                                                                                                                              
                                                                                                                                                                                                                
                    // 初始化 16 个累加器寄存器 (全 0)                                                                                                                                                          
                    float16x8_t v_c0_low = vdupq_n_f16(0.0f); float16x8_t v_c0_high = vdupq_n_f16(0.0f);                                                                                                        
                    float16x8_t v_c1_low = vdupq_n_f16(0.0f); float16x8_t v_c1_high = vdupq_n_f16(0.0f);                                                                                                        
                    float16x8_t v_c2_low = vdupq_n_f16(0.0f); float16x8_t v_c2_high = vdupq_n_f16(0.0f);                                                                                                        
                    float16x8_t v_c3_low = vdupq_n_f16(0.0f); float16x8_t v_c3_high = vdupq_n_f16(0.0f);                                                                                                        
                    float16x8_t v_c4_low = vdupq_n_f16(0.0f); float16x8_t v_c4_high = vdupq_n_f16(0.0f);                                                                                                        
                    float16x8_t v_c5_low = vdupq_n_f16(0.0f); float16x8_t v_c5_high = vdupq_n_f16(0.0f);                                                                                                        
                    float16x8_t v_c6_low = vdupq_n_f16(0.0f); float16x8_t v_c6_high = vdupq_n_f16(0.0f);                                                                                                        
                    float16x8_t v_c7_low = vdupq_n_f16(0.0f); float16x8_t v_c7_high = vdupq_n_f16(0.0f);                                                                                                        
                                                                                                                                                                                                                
                    // 进入微内核 (Uk = 2 软件流水线展开)                                                                                                                                                       
                    for (int k = 0; k < K; k += 2) {                                                                                                                                                            
                                                                                                                                                                                                                
                        // 【阶段 A：并发读取与解包权重】                                                                                                                                                       
                        uint8x8_t v_w_packed_0 = vld1_u8(ptr_w);                                                                                                                                                
                        uint8x8_t v_w_packed_1 = vld1_u8(ptr_w + 8);                                                                                                                                            
                        ptr_w += 16;                                                                                                                                                                            
                                                                                                                                                                                                                
                        uint8x16_t v_w_128_0 = vcombine_u8(v_w_packed_0, vdup_n_u8(0));                                                                                                                         
                        uint8x16_t v_w_128_1 = vcombine_u8(v_w_packed_1, vdup_n_u8(0));                                                                                                                         
                                                                                                                                                                                                                
                        uint8x8_t v_low_int8_0  = vget_low_u8(vshrq_n_u8(vshlq_n_u8(v_w_128_0, 4), 4));                                                                                                         
                        uint8x8_t v_high_int8_0 = vget_low_u8(vshrq_n_u8(v_w_128_0, 4));                                                                                                                        
                        uint8x8_t v_low_int8_1  = vget_low_u8(vshrq_n_u8(vshlq_n_u8(v_w_128_1, 4), 4));                                                                                                         
                        uint8x8_t v_high_int8_1 = vget_low_u8(vshrq_n_u8(v_w_128_1, 4));                                                                                                                        
                                                                                                                                                                                                                
                        // 一步完成反量化：Float16 = Bias + Int8 * Scale                                                                                                                                        
                        float16x8_t v_w_fp16_low_0  = vfmaq_f16(v_bias, vcvtq_f16_u16(vmovl_u8(v_low_int8_0)),  v_scale);                                                                                       
                        float16x8_t v_w_fp16_high_0 = vfmaq_f16(v_bias, vcvtq_f16_u16(vmovl_u8(v_high_int8_0)), v_scale);                                                                                       
                        float16x8_t v_w_fp16_low_1  = vfmaq_f16(v_bias, vcvtq_f16_u16(vmovl_u8(v_low_int8_1)),  v_scale);                                                                                       
                        float16x8_t v_w_fp16_high_1 = vfmaq_f16(v_bias, vcvtq_f16_u16(vmovl_u8(v_high_int8_1)), v_scale);                                                                                       
                                                                                                                                                                                                                
                        // 【阶段 B：极限火力倾泻 (FMA 并发，填满流水线气泡)】                                                                                                                                  
                        // Row 0                                                                                                                                                                                
                        float16x8_t v_act0_0 = vld1q_dup_f16(ptr_act + 0);                                                                                                                                      
                        float16x8_t v_act0_1 = vld1q_dup_f16(ptr_act + 8);                                                                                                                                      
                        v_c0_low  = vfmaq_f16(v_c0_low, v_w_fp16_low_0,  v_act0_0);                                                                                                                             
                        v_c0_low  = vfmaq_f16(v_c0_low, v_w_fp16_low_1,  v_act0_1);                                                                                                                             
                        v_c0_high = vfmaq_f16(v_c0_high, v_w_fp16_high_0, v_act0_0);                                                                                                                            
                        v_c0_high = vfmaq_f16(v_c0_high, v_w_fp16_high_1, v_act0_1);                                                                                                                            
                                                                                                                                                                                                                
                        // Row 1                                                                                                                                                                                
                        float16x8_t v_act1_0 = vld1q_dup_f16(ptr_act + 1);                                                                                                                                      
                        float16x8_t v_act1_1 = vld1q_dup_f16(ptr_act + 9);                                                                                                                                      
                        v_c1_low  = vfmaq_f16(v_c1_low, v_w_fp16_low_0,  v_act1_0);                                                                                                                             
                        v_c1_low  = vfmaq_f16(v_c1_low, v_w_fp16_low_1,  v_act1_1);                                                                                                                             
                        v_c1_high = vfmaq_f16(v_c1_high, v_w_fp16_high_0, v_act1_0);                                                                                                                            
                        v_c1_high = vfmaq_f16(v_c1_high, v_w_fp16_high_1, v_act1_1);                                                                                                                            
                                                                                                                                                                                                                
                        // Row 2                                                                                                                                                                                
                        float16x8_t v_act2_0 = vld1q_dup_f16(ptr_act + 2);                                                                                                                                      
                        float16x8_t v_act2_1 = vld1q_dup_f16(ptr_act + 10);                                                                                                                                     
                        v_c2_low  = vfmaq_f16(v_c2_low, v_w_fp16_low_0,  v_act2_0);                                                                                                                             
                        v_c2_low  = vfmaq_f16(v_c2_low, v_w_fp16_low_1,  v_act2_1);                                                                                                                             
                        v_c2_high = vfmaq_f16(v_c2_high, v_w_fp16_high_0, v_act2_0);                                                                                                                            
                        v_c2_high = vfmaq_f16(v_c2_high, v_w_fp16_high_1, v_act2_1);                                                                                                                            
                                                                                                                                                                                                                
                        // Row 3                                                                                                                                                                                
                        float16x8_t v_act3_0 = vld1q_dup_f16(ptr_act + 3);                                                                                                                                      
                        float16x8_t v_act3_1 = vld1q_dup_f16(ptr_act + 11);                                                                                                                                     
                        v_c3_low  = vfmaq_f16(v_c3_low, v_w_fp16_low_0,  v_act3_0);                                                                                                                             
                        v_c3_low  = vfmaq_f16(v_c3_low, v_w_fp16_low_1,  v_act3_1);                                                                                                                             
                        v_c3_high = vfmaq_f16(v_c3_high, v_w_fp16_high_0, v_act3_0);                                                                                                                            
                        v_c3_high = vfmaq_f16(v_c3_high, v_w_fp16_high_1, v_act3_1);                                                                                                                            
                                                                                                                                                                                                                
                        // Row 4                                                                                                                                                                                
                        float16x8_t v_act4_0 = vld1q_dup_f16(ptr_act + 4);                                                                                                                                      
                        float16x8_t v_act4_1 = vld1q_dup_f16(ptr_act + 12);                                                                                                                                     
                        v_c4_low  = vfmaq_f16(v_c4_low, v_w_fp16_low_0,  v_act4_0);                                                                                                                             
                        v_c4_low  = vfmaq_f16(v_c4_low, v_w_fp16_low_1,  v_act4_1);                                                                                                                             
                        v_c4_high = vfmaq_f16(v_c4_high, v_w_fp16_high_0, v_act4_0);                                                                                                                            
                        v_c4_high = vfmaq_f16(v_c4_high, v_w_fp16_high_1, v_act4_1);                                                                                                                            
                                                                                                                                                                                                                
                        // Row 5                                                                                                                                                                                
                        float16x8_t v_act5_0 = vld1q_dup_f16(ptr_act + 5);                                                                                                                                      
                        float16x8_t v_act5_1 = vld1q_dup_f16(ptr_act + 13);                                                                                                                                     
                        v_c5_low  = vfmaq_f16(v_c5_low, v_w_fp16_low_0,  v_act5_0);                                                                                                                             
                        v_c5_low  = vfmaq_f16(v_c5_low, v_w_fp16_low_1,  v_act5_1);                                                                                                                             
                        v_c5_high = vfmaq_f16(v_c5_high, v_w_fp16_high_0, v_act5_0);                                                                                                                            
                        v_c5_high = vfmaq_f16(v_c5_high, v_w_fp16_high_1, v_act5_1);                                                                                                                            
                                                                                                                                                                                                                
                        // Row 6                                                                                                                                                                                
                        float16x8_t v_act6_0 = vld1q_dup_f16(ptr_act + 6);                                                                                                                                      
                        float16x8_t v_act6_1 = vld1q_dup_f16(ptr_act + 14);                                                                                                                                     
                        v_c6_low  = vfmaq_f16(v_c6_low, v_w_fp16_low_0,  v_act6_0);                                                                                                                             
                        v_c6_low  = vfmaq_f16(v_c6_low, v_w_fp16_low_1,  v_act6_1);                                                                                                                             
                        v_c6_high = vfmaq_f16(v_c6_high, v_w_fp16_high_0, v_act6_0);                                                                                                                            
                        v_c6_high = vfmaq_f16(v_c6_high, v_w_fp16_high_1, v_act6_1);                                                                                                                            
                                                                                                                                                                                                                
                        // Row 7                                                                                                                                                                                
                        float16x8_t v_act7_0 = vld1q_dup_f16(ptr_act + 7);                                                                                                                                      
                        float16x8_t v_act7_1 = vld1q_dup_f16(ptr_act + 15);                                                                                                                                     
                        v_c7_low  = vfmaq_f16(v_c7_low, v_w_fp16_low_0,  v_act7_0);                                                                                                                             
                        v_c7_low  = vfmaq_f16(v_c7_low, v_w_fp16_low_1,  v_act7_1);                                                                                                                             
                        v_c7_high = vfmaq_f16(v_c7_high, v_w_fp16_high_0, v_act7_0);                                                                                                                            
                        v_c7_high = vfmaq_f16(v_c7_high, v_w_fp16_high_1, v_act7_1);                                                                                                                            
                                                                                                                                                                                                                
                        // 步进 16 个元素 (因为内循环包含了 k 和 k+1，且 A 矩阵交错按 8 行存储)                                                                                                                 
                        ptr_act += 16;                                                                                                                                                                          
                    }                                                                                                                                                                                           
                                                                                                                                                                                                                
                    // 【步骤 4：Store (将物理寄存器写回输出矩阵内存)】                                                                                                                                         
                    float16_t* ptr_out = C + (m * N) + n;                                                                                                                                                       
                                                                                                                                                                                                                
                    // Row 0 - 7                                                                                                                                                                                
                    vst1q_f16(ptr_out + 0 * N, v_c0_low); vst1q_f16(ptr_out + 0 * N + 8, v_c0_high);                                                                                                            
                    vst1q_f16(ptr_out + 1 * N, v_c1_low); vst1q_f16(ptr_out + 1 * N + 8, v_c1_high);                                                                                                            
                    vst1q_f16(ptr_out + 2 * N, v_c2_low); vst1q_f16(ptr_out + 2 * N + 8, v_c2_high);                                                                                                            
                    vst1q_f16(ptr_out + 3 * N, v_c3_low); vst1q_f16(ptr_out + 3 * N + 8, v_c3_high);                                                                                                            
                    vst1q_f16(ptr_out + 4 * N, v_c4_low); vst1q_f16(ptr_out + 4 * N + 8, v_c4_high);                                                                                                            
                    vst1q_f16(ptr_out + 5 * N, v_c5_low); vst1q_f16(ptr_out + 5 * N + 8, v_c5_high);                                                                                                            
                    vst1q_f16(ptr_out + 6 * N, v_c6_low); vst1q_f16(ptr_out + 6 * N + 8, v_c6_high);                                                                                                            
                    vst1q_f16(ptr_out + 7 * N, v_c7_low); vst1q_f16(ptr_out + 7 * N + 8, v_c7_high);                                                                                                            
                                                                                                                                                                                                                
                }                                                                                                                                                                                               
            }                                                                                                                                                                                                   
}                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                        
int main() {                                                                                                                                                                                            
        // 模拟真实大语言模型 (LLM) 中的一层矩阵维度                                                                                                                                                        
        int M = 1024; // Token 序列长度 (Batch Size)                                                                                                                                                        
        int N = 4096; // 输出维度                                                                                                                                                                           
        int K = 4096; // 输入特征维度                                                                                                                                                                       
                                                                                                                                                                                                            
        std::cout << ">>> 分配超大内存 (M=" << M << ", N=" << N << ", K=" << K << ")...\n";                                                                                                                 
        std::vector<float16_t> A(M * K, 1.0f);                                                                                                                                                              
        std::vector<uint8_t> W(K * N / 2, 0x5c); // W4A16压缩尺寸                                                                                                                                           
        std::vector<float16_t> C(M * N, 0.0f);                                                                                                                                                              
                                                                                                                                                                                                            
        std::cout << ">>> 预热算子 (唤醒 CPU 频率和 Cache)...\n";                                                                                                                                           
        gemm_m4_w4a16(A.data(), W.data(), C.data(), M, N, K);                                                                                                                                               
                                                                                                                                                                                                            
        int num_runs = 10;                                                                                                                                                                                  
        std::cout << ">>> 开始 Benchmark (连续暴走 " << num_runs << " 次)...\n";                                                                                                                            
                                                                                                                                                                                                            
        // 启动高精度计时器                                                                                                                                                                                 
        auto start_time = std::chrono::high_resolution_clock::now();                                                                                                                                        
                                                                                                                                                                                                            
        for (int i = 0; i < num_runs; i++) {                                                                                                                                                                
            gemm_m4_w4a16(A.data(), W.data(), C.data(), M, N, K);                                                                                                                                           
        }                                                                                                                                                                                                   
                                                                                                                                                                                                            
        // 停止计时                                                                                                                                                                                         
        auto end_time = std::chrono::high_resolution_clock::now();                                                                                                                                          
        std::chrono::duration<double> diff = end_time - start_time;                                                                                                                                         
        double avg_time_sec = diff.count() / num_runs;                                                                                                                                                      
                                                                                                                                                                                                            
        // 计算 GFLOPS (Giga Floating-point Operations Per Second)                                                                                                                                          
        // 乘加 = 2次操作，总操作数 = 2 * M * N * K                                                                                                                                                         
        double total_flops = 2.0 * M * N * K;                                                                                                                                                               
        double gflops = (total_flops / avg_time_sec) / 1e9;                                                                                                                                                 
                                                                                                                                                                                                            
        std::cout << "--------------------------------------\n";                                                                                                                                            
        std::cout << "[Benchmark 物理极速报告]\n";                                                                                                                                                          
        std::cout << "单次平均耗时 : " << avg_time_sec * 1000.0 << " ms\n";                                                                                                                                 
        std::cout << "绝对算力吞吐 : " << gflops << " GFLOPS\n";                                                                                                                                            
        std::cout << "--------------------------------------\n";                                                                                                                                            
                                                                                                                                                                                                            
        return 0;                                                                                                                                                                                           
    }                                                                                                                                                                                                       
                                                                             